version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    # volumes:
    #    - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  api:
    build: ./server
    container_name: api_backend
    ports:
      - '5000:5000'
    environment:
      DB_HOST: host.docker.internal
      DB_USER: pgadmin
      DB_PASSWORD: pgadmin
    
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    
    stdin_open: true
    tty: true

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    client:
    server: